[server]
control-plane ansible_host=13.62.223.101

[agents]
worker-1 ansible_host=51.20.119.139
worker-2 ansible_host=16.171.115.241

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/taskapp-key
ansible_python_interpreter=/usr/bin/python3